name: Copier Update

on:
  workflow_dispatch:
  schedule:
    - cron: '3 16 * * *'

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6
        with:
          python-version: '3.14'
      - uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7
      - id: copier-update
        run: uvx copier update --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults
      - id: copier-recopy
        if: ${{ failure() && steps.copier-update.conclusion == 'failure' }}
        run: uvx copier recopy --trust --vcs-ref main --exclude src --exclude test --exclude package.json --defaults --overwrite
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        if: ${{ steps.copier-update.conclusion == 'success' }}
        with:
          branch: chore/copier-update
          title: 'chore(deps): run `copier update`'
          commit-message: 'chore(deps): run `copier update`'
      - uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8
        if: ${{ failure() && steps.copier-recopy.conclusion == 'success' }}
        with:
          branch: chore/copier-recopy
          title: 'chore(deps): run `copier recopy`'
          commit-message: 'chore(deps): run `copier recopy`'
